const programmingLanguages = [
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "PHP",
  "TypeScript",
  "Ruby",
  "Swift",
  "Go",
  "Kotlin",
  "Rust",
  "SQL",
  "HTML",
  "CSS",
  "R",
  "Scala",
  "Perl",
  "Objective-C",
  "Assembly",
  "Dart",
  "Shell",
  "Lua",
  "MATLAB",
  "Haskell",
  "Groovy",
  "Julia",
  "Elixir",
  "Clojure",
  "VBA",
  "F#",
  "Delphi",
  "COBOL",
  "PL/SQL",
  "Ada",
  "Scheme",
  "Lisp",
  "PowerShell",
  "Prolog",
  "D",
  "ABAP",
  "Fortran",
  "Apex",
  "Visual Basic",
  "ActionScript",
  "Django",
  "Vue.js",
  "React",
  "Angular",
  "Node.js",
  "Express.js",
  "Spring",
  "Flask",
  "Laravel",
  "Symfony",
  "Ruby on Rails",
  "ASP.NET",
  "ASP.NET Core",
  "Django",
  "Flask",
  "Hibernate",
  "jQuery",
  "ASP",
  "ASP.NET MVC",
  "ASP.NET Web API",
  "Redux",
  "Vuex",
  "GraphQL",
  "Apache Kafka",
  "GraphQL",
  "RxJS",
  "D3.js",
  "Unity",
  "OpenGL",
  "DirectX",
  "Vulkan",
  "OpenCL",
  "CUDA",
  "Metal",
  "SFML",
  "SDL",
  "Pandas",
  "NumPy",
  "TensorFlow",
  "Keras",
  "PyTorch",
  "Scikit-learn",
  "Matplotlib",
  "Seaborn",
  "Beautiful Soup",
  "Django REST framework",
  "Flask-RESTful",
  "Express.js",
  "Meteor",
  "Next.js",
  "Gatsby",
  "Nuxt.js",
  "Strapi",
  "LoopBack",
  "Feathers",
  "Koa",
  "Sails.js",
  "AdonisJS",
  "Ember.js",
  "Backbone.js",
  "Knockout.js",
  "Polymer",
  "Aurelia",
  "Mithril",
  "Svelte",
  "Stencil",
  "Quasar Framework",
  "Electron",
  "React Native",
  "NativeScript",
  "Ionic",
  "Flutter",
  "Xamarin",
  "Cordova",
  "PhoneGap",
  "Titanium",
  "RhoMobile",
  "Appcelerator",
  "PWA",
  "RubyMotion",
  "Apache Cordova",
  "TensorFlow.js",
  "Keras.js",
  "PyTorch.js",
  "TorchScript",
  "CNTK",
  "MXNet",
  "Deeplearn.js",
  "H2O.ai",
  "XGBoost",
  "LightGBM",
  "CatBoost",
  "Scikit-optimize",
  "TPOT",
  "Hyperopt",
  "Auto-sklearn",
  "AdaBoost",
  "Bagging",
  "Gradient Boosting",
  "Random Forest",
  "Decision Tree",
  "Logistic Regression",
  "K-Nearest Neighbors (KNN)",
  "Support Vector Machine (SVM)",
  "Naive Bayes",
  "Principal Component Analysis (PCA)",
  "Linear Discriminant Analysis (LDA)",
  "K-Means Clustering",
  "Hierarchical Clustering",
  "DBSCAN",
  "Mean Shift",
  "Expectation-Maximization (EM)",
  "Isolation Forest",
  "Local Outlier Factor (LOF)",
  "One-Class SVM",
  "Autoencoder",
  "Variational Autoencoder (VAE)",
  "Generative Adversarial Network (GAN)",
  "Conditional GAN (CGAN)",
  "CycleGAN",
  "Pix2Pix",
  "StyleGAN",
  "BERT",
  "GPT",
  "Transformer",
  "ResNet",
  "VGG",
  "Inception",
  "MobileNet",
  "DenseNet",
  "AlexNet",
  "Capsule Networks",
  "U-Net",
  "YOLO",
  "Mask R-CNN",
  "Faster R-CNN",
  "RCNN",
  "SSD",
  "RetinaNet",
  "PointNet",
  "PointNet++",
  "GloVe",
  "Word2Vec",
  "FastText",
  "ELMo",
  "BERT",
  "GPT",
  "Transformer",
  "LSTM",
  "GRU",
  "BiLSTM",
  "Seq2Seq",
  "Attention Mechanism",
  "Beam Search",
  "Reinforcement Learning",
  "Q-Learning",
  "Deep Q-Network (DQN)",
  "Policy Gradient Methods",
  "Actor-Critic Methods",
  "Temporal Difference Learning (TD Learning)",
  "Monte Carlo Methods",
  "SARSA",
  "AlphaGo",
  "AlphaZero",
  "OpenAI Five",
  "DeepMind",
  "OpenAI",
  "Google Brain",
  "Facebook AI Research (FAIR)",
  "Microsoft Research",
  "Amazon AI",
  "IBM Watson",
  "Apple AI",
  "Baidu AI",
  "Alibaba AI",
  "Tencent AI",
  "Huawei AI",
  "SenseTime",
  "Megvii (Face++)",
  "OpenAI GPT-3",
  "Microsoft Azure",
  "Amazon Web Services (AWS)",
  "Google Cloud Platform (GCP)",
  "IBM Cloud",
  "Alibaba Cloud",
  "DigitalOcean",
  "Heroku",
  "Azure DevOps",
  "GitHub Actions",
  "Travis CI",
  "CircleCI",
  "Jenkins",
  "GitLab CI",
  "Docker",
  "Kubernetes",
  "Vagrant",
  "Ansible",
  "Terraform",
  "Puppet",
  "Chef",
  "AWS Lambda",
  "Google Cloud Functions",
  "Azure Functions",
  "Firebase",
  "Netlify",
  "Vercel",
  "Render",
  "Zeit",
  "Heroku",
  "DigitalOcean App Platform",
  "Platform.sh",
  "GoDaddy",
  "HostGator",
  "Bluehost",
  "SiteGround",
  "DreamHost",
  "WP Engine",
  "Squarespace",
  "Wix",
  "Shopify",
  "Magento",
  "BigCommerce",
  "WooCommerce",
  "OpenCart",
  "PrestaShop",
  "Volusion",
  "3dcart",
  "Weebly",
  "Drupal",
  "Joomla",
  "WordPress",
  "Ghost",
];
export default programmingLanguages;
